data:
  root: "data/idd20k_lite"
  num_classes: 7
  ignore_index: 255
  image_size: [224, 320]    
  batch_size: 256          
  num_workers: 2            

  class_names: ["drivable", "non-drivable", "living-things", "vehicles", "road-side-objs", "far-objects", "sky"]


training:
  
  optimizer: "adamw"
  lr: 0.0024               
  weight_decay: 0.01        
  
 
  scheduler: "cosine"
  
  
  epochs: 200
  class_weights: true       
  lovasz_weight: 0.5       
  amp: true                 
  grad_clip_norm: 1.0
  
  
  backbone_lr_multiplier: 0.75
  classifier_lr_multiplier: 4.0  
      
  
  
  val_every: 1              
  save_best: true
  accum_steps: 1
  early_stopping:
    patience: 20
    min_delta: 0.005    

augmentation:
  
  scale_min: 1.0           
  scale_max: 1.2           
  horizontal_flip: 0.5    
  rotation: 0.0             
  
  
  brightness: 0.2          
  contrast: 0.2            
  saturation: 0.2          
  blur_p: 0.05             

  
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

experiment:
  name: "idd_base_experiment"
  save_dir: "runs"
  seed: 42
