# Base configuration for IDD semantic segmentation
data:
  root: "data/idd20k_lite"
  num_classes: 7
  ignore_index: 255
  image_size: [512, 512]
  batch_size: 8
  num_workers: 4
  
  # Class names for IDD Lite
  class_names: ["road", "sidewalk", "building", "wall", "fence", "pole", "traffic_sign"]

model:
  name: "deeplabv3"  # deeplabv3, fcn
  pretrained: true

training:
  epochs: 100
  
  # SGD optimizer settings
  optimizer: "sgd"
  lr: 0.01
  momentum: 0.9
  weight_decay: 1e-4
  
  # Differential learning rates
  backbone_lr_multiplier: 1.0
  classifier_lr_multiplier: 10.0
  
  # Polynomial LR scheduler
  scheduler: "poly"
  poly_power: 0.9
  
  # Mixed precision training
  amp: true
  
  # Auxiliary loss weight
  aux_loss_weight: 0.4
  
  # Validation
  val_every: 5
  save_best: true

augmentation:
  # Geometric transforms
  horizontal_flip: 0.5
  rotation: 10
  
  # Photometric transforms  
  brightness: 0.1
  contrast: 0.1
  saturation: 0.1
  
  # Normalization (ImageNet stats)
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

experiment:
  name: "idd_segmentation"
  save_dir: "runs"
  seed: 42 